version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    volumes:
      - ./tmp:/app/tmp
    environment:
      - NODE_ENV=production
    restart: always 